require('config.nvim-tree')
require('config.toggleterm')
require('config.telescope')
require('config.alpha')
require('config.lualine')
require('impatient')
require("nvim-autopairs").setup {}
require('config.theme')
require('config.barbar')
require('config.theme')
require('config.treesitter')
require('config.blankline')
require('keybinds')
require("nvim-lsp-installer").setup()
require('config.Wilder')
require('config.coq')
